### ISSUE TITLE
[ADD] Add colors in the output to separate open and closed ports.

### ISSUE THREAD

**Issue by theinit01** [theinit01/portscanner#2]
Add colors in the output to separate open and closed ports. For e.g., Red for closed and green for open

**Comment by georgioupanayiotis** [comment]
@theinit01 please assign this to me

**Comment by Rishika631** [comment]
@theinit01 please assign it to me.

**Comment by Rishika631** [comment]
@theinit01 now if there is any open port then closed ports are not getting displayed and only open ports are showing so should I remove this condition so that it displays open and closed ports with different colors or keep it as it is just add colors to the ports?

**Comment by theinit01** [comment]
As one of the two type of ports are listed, just add colours onto what are displayed. Let the conditions be as it is.

**Comment by Rishika631** [comment]
okay

**Comment by Rishika631** [comment]
I have raised a PR. Do let me know if any changes are needed.
