### ISSUE TITLE
Add port service identification functionality

### ISSUE THREAD

**Issue by theinit01** [theinit01/portscanner#8]
Extend the script to not only detect open/closed ports but also attempt to identify the services running on the open ports by inspecting banners or sending protocol-specific probes.

**Comment by Rishika631** [comment]
please assign this to me

**Comment by theinit01** [comment]
@Rishika631, I am assigning this issue to you. Feel free to submit a PR.

**Comment by Rishika631** [comment]
I have raised the PR for this.
